siteTitle='Digitransit'
headerColor='#39b6db'
ghPagesURLPrefix='/'
[i18n.fi]
  users='Käyttäjille'
  developers='Kehittäjille'
  municipalities='Kunnille'
  news='uutiset'
[i18n.en]
  users='for Users'
  developers='for Developers'
  municipalities='for Municipalities'
  news='news'
