siteTitle='Digitransit'
headerColor='#39b6db'
ghPagesURLPrefix='/'
[[translations]]
  [i18n.fi]
    users='Käyttäjille'
    developers='Kehittäjille'
    muncipalities='Kunnille'
  [i18n.en]
    users='for Users'
    developers='for Developers'
    muncipalities='for Muncipalities'
